const main=document.querySelector('main');
const viewer=document.querySelector('#viewer');
const imageUrl=id=>id?.startsWith('/')?id:'/assets/'+id+'.jpg';
const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const image=(id,alt,lazy=true)=>`<img src="${esc(imageUrl(id))}" alt="${esc(alt)}" ${lazy?'loading="lazy"':'fetchpriority="high"'} decoding="async">`;
function categoryCover(c){if(c.cover?.startsWith('/'))return c.cover;const ids={animation:'tree',ai:'water',concept:'concept',ip:'yun',film:'blind',words:'essay4'};const p=projects.find(x=>x.id===ids[c.id]);return p?._revision>0&&p.cover?p.cover:c.cover;}
const tx=key=>esc(siteContent[key]||'');
const lines=key=>tx(key).replace(/\n/g,'<br>');
const mailLink=(label=siteContent.email)=>siteContent.email?`<a href="mailto:${esc(encodeURIComponent(siteContent.email))}">${esc(label)} ↗</a>`:'';
const phoneLink=()=>siteContent.phone?`<a href="tel:${esc(encodeURIComponent(siteContent.phone))}">${tx('phoneLabel')} ${tx('phone')} ↗</a>`:'';
function refreshChrome(){const s=siteContent;document.querySelector('.brand').innerHTML=tx('name')+'<span>'+tx('englishName')+'</span>';document.querySelector('.brand').setAttribute('aria-label',s.name);document.querySelector('header nav').innerHTML=`<a href="/#/">${tx('navWorks')}</a><a href="/#/about">${tx('navAbout')}</a>${canEdit?'<a href="/manage">'+tx('navManage')+'</a>':''}`;document.querySelector('.header-note').textContent=s.headerNote;const f=document.querySelector('footer');f.firstElementChild.textContent=s.name+' / '+s.englishName;f.querySelector('span').textContent=s.footerText;document.querySelector('#to-top').textContent=s.topLabel+' ↑';viewer.querySelector('.close').textContent=s.closeLabel+' ×';document.querySelector('meta[name=description]').content=s.metaDescription;const icon=document.querySelector('link[rel=icon]');icon.dataset.defaultIcon??=icon.href;icon.href=s.favicon||icon.dataset.defaultIcon;document.body.classList.toggle('motion-disabled',!s.motion)}
function home(){return `<section class="hero"><div><div class="eyebrow">${tx('name')} / ${tx('identity')}</div><h1>${tx('englishName')}<span></span></h1></div><div class="hero-copy"><h2>${lines('heroTitle')}</h2><p>${lines('heroDescription')}</p><p class="signature">${mailLink()}</p></div></section><div class="section-line"><span>${tx('indexTitle')}</span><span>${String(categories.length).padStart(2,'0')} ${tx('directionUnit')}</span></div><section class="category-grid" aria-label="作品类别">${categories.map((c,i)=>`<a class="category ${c.id}" href="#/category/${c.id}"><div class="category-visual">${image(categoryCover(c),c.name+'代表作品',i>1)}<span class="index">${String(i+1).padStart(2,'0')} / ${esc(c.tag??c.id.toUpperCase())}</span><span class="arrow" aria-hidden="true">↗</span></div><div class="category-info"><h3>${esc(c.name)}</h3><span>${projects.filter(p=>p.cat===c.id).length} ${tx('groupUnit')}</span></div><div class="category-sub">${esc(c.en)}</div></a>`).join('')}</section><section class="home-end"><p>${tx('name')} / ${tx('identity')}<br><span class="eyebrow">${tx('keywords')}</span></p><span class="text-link">${phoneLink()}</span><span class="text-link">${mailLink(siteContent.emailLabel)}</span></section>`;}
function fact(label,text,cls=''){return text?`<div class="fact"><dt>${label}</dt><dd class="${cls}">${esc(text)}</dd></div>`:'';}
function disclosure(title,text){return text?`<details><summary>${title}</summary><p>${esc(text)}</p></details>`:'';}
function still(p,src,lazy=true){return `<button class="media-button ${p.portrait?'portrait':''}" data-view="${esc(src)}" aria-label="放大查看${esc(p.title)}">${image(src,p.title+'作品画面',lazy)}<span class="media-label">${p.cat==='words'?tx('readLabel'):tx('viewImageLabel')} ↗</span></button>`;}
function video(p){return `<video class="project-video ${p.portrait?'portrait':''}" controls playsinline preload="none" poster="${esc(imageUrl(p.cover||p.images[0]))}" src="${esc(p.video)}" aria-label="${esc(p.title)}影片">当前浏览器不支持该视频，请更换浏览器。</video>`;}
function project(p,i){return `<article class="project" id="project-${p.id}"><div class="project-media"><div class="media-stage">${p.video?video(p):still(p,p.cover||p.images[0],i>0)}</div>${p.images.length||p.video?`<div class="thumbs" aria-label="切换作品画面">${p.video?`<button class="video-thumb" data-inline-play="${p.id}" aria-label="播放${esc(p.title)}">▷ ${tx('videoLabel')}</button>`:''}${p.images.map((im,j)=>`<button data-thumb="${esc(im)}" data-project="${p.id}" aria-label="${esc(p.title)}画面 ${j+1}" aria-pressed="${!p.video&&j===0}">${image(im,p.title+'画面 '+(j+1))}</button>`).join('')}</div>`:''}</div><div class="project-copy"><div class="project-heading"><div><span class="eyebrow">${esc(p.type)}</span><h2>${esc(p.title)}</h2></div><span class="project-num">${String(i+1).padStart(2,'0')}</span></div><p class="intro">${esc(p.intro)}</p><dl class="facts">${fact(tx('toolsLabel'),p.tools)}${fact(tx('contributionLabel'),p.contribution)}${fact(tx('roleLabel'),p.role)}${fact(tx('awardLabel'),p.award,'award')}</dl>${disclosure(tx('ideaLabel'),p.idea)}${disclosure(tx('processLabel'),p.process)}${disclosure(tx('challengeLabel'),p.challenge)}${disclosure(tx('solutionLabel'),p.solution)}${p.video?`<button class="action" data-inline-play="${p.id}">${tx('playLabel')} <span>▷</span></button>`:''}</div></article>`;}
function category(id){const c=categories.find(x=>x.id===id);if(!c)return notFound();const items=projects.filter(x=>x.cat===id);document.title=c.name+' — '+siteContent.name;return `<a class="back" href="#/">← ${tx('backLabel')}</a><section class="category-heading"><div><div class="eyebrow">${esc(c.en)}</div><h1>${esc(c.name)}</h1><p>${esc(c.desc)}</p></div><span>${String(items.length).padStart(2,'0')}</span></section><nav class="category-nav" aria-label="作品分类">${categories.map(x=>`<a href="#/category/${x.id}" ${x.id===id?'aria-current="page"':''}>${esc(x.name)}</a>`).join('')}</nav><section class="${id==='words'?'reading':''}" aria-label="${esc(c.name)}作品">${items.map(project).join('')}</section>`;}
function about(){return `<a class="back" href="#/">← ${tx('backLabel')}</a><section class="about"><div class="eyebrow">${tx('aboutEyebrow')}</div><h1>${tx('name')}</h1><div class="lead">${lines('aboutLead')}</div><p>${lines('aboutDescription')}</p>${siteContent.aboutImage?'<div class="about-cover">'+image(siteContent.aboutImage,siteContent.name+'展示图片',false)+'</div>':''}<div class="about-grid"><div><h2>${tx('themeTitle')}</h2><p>${lines('themeText')}</p><a class="text-link" href="#/">${tx('allWorksLabel')} ↗</a></div><div><h2>${tx('contactTitle')}</h2><p>${mailLink()}<br>${phoneLink()}</p></div></div></section>`;}
function notFound(){return `<section class="error"><h1>${tx('notFoundTitle')}</h1><a class="text-link" href="#/">${tx('backLabel')}</a></section>`;}
function render(){const path=location.hash.replace(/^#/,'')||'/';refreshChrome();document.title=siteContent.pageTitle;if(location.pathname==='/manage'){document.title=siteContent.navManage+' — '+siteContent.name;main.innerHTML=management();initEditor();initSettings();}else main.innerHTML=path==='/'?home():path==='/about'?about():path.startsWith('/category/')?category(path.split('/')[2]):notFound();if(viewer.open)viewer.close();window.scrollTo(0,0);}
main.addEventListener('click',e=>{const thumb=e.target.closest('[data-thumb]');if(thumb){const box=thumb.closest('.project-media'),p=projects.find(x=>x.id===thumb.dataset.project);box.querySelector('video')?.pause();box.querySelector('.media-stage').innerHTML=still(p,thumb.dataset.thumb,false);box.querySelectorAll('[data-thumb]').forEach(b=>b.setAttribute('aria-pressed',String(b===thumb)));return;}const b=e.target.closest('[data-view]');if(b){viewer.classList.toggle('document-view',b.classList.contains('portrait'));viewer.querySelector('.viewer-content').innerHTML=image(b.dataset.view,b.getAttribute('aria-label'),false);viewer.showModal();}const play=e.target.closest('[data-inline-play]');if(play){const p=projects.find(x=>x.id===play.dataset.inlinePlay),stage=play.closest('.project').querySelector('.media-stage');if(p?.video){document.querySelectorAll('video').forEach(v=>v.pause());if(!stage.querySelector('video'))stage.innerHTML=video(p);stage.querySelector('video').play().catch(()=>{});stage.scrollIntoView({block:'center',behavior:'smooth'});}}});
viewer.querySelector('.close').addEventListener('click',()=>viewer.close());viewer.addEventListener('click',e=>{if(e.target===viewer)viewer.close()});viewer.addEventListener('close',()=>{viewer.querySelector('.viewer-content').innerHTML=''});
document.querySelector('#to-top').addEventListener('click',e=>{e.preventDefault();window.scrollTo({top:0,behavior:'smooth'});main.focus({preventScroll:true});});
document.querySelector('.skip').addEventListener('click',e=>{e.preventDefault();main.focus();});
window.addEventListener('hashchange',()=>{render();main.focus({preventScroll:true});});
if(location.pathname!=='/manage')render();
(async()=>{try{const [content,session]=await Promise.all([api('/api/portfolio'),api('/api/session')]);projects=content.projects;siteContent={...SITE_DEFAULTS,...content.site};categories=content.categories||categories;siteRevision=content.siteRevision||0;orderRevisions=content.orderRevisions||{};canEdit=session.canEdit;render();}catch(e){if(location.pathname==='/manage'){main.innerHTML='<section class="about"><h1>作品管理暂时无法载入</h1><p>请刷新页面重试。已保存的作品不会受影响。</p></section>';}else{const note=document.createElement('div');note.className='load-notice';note.textContent='暂时无法读取最新内容，当前展示基础版本。请稍后刷新。';document.querySelector('header').after(note)}}})();

