let editingProject=null,editorBusy=false,editorDirty=false,uploadAbort=null,canEdit=false;
const editorFields=[['title','作品名称'],['type','项目类型'],['intro','项目简介'],['tools','使用工具'],['contribution','我负责的内容'],['idea','设计思路'],['process','制作过程'],['challenge','项目难点'],['solution','解决办法'],['award','成果与奖项'],['role','作品性质']];
async function api(url,options={}){const r=await fetch(url,{credentials:'same-origin',...options});let data;try{data=await r.json()}catch{throw Error('连接暂时中断，请稍后重试。')}if(!r.ok)throw Object.assign(Error(data.error||'操作未完成，请重试。'),{status:r.status});return data;}
function management(){if(!canEdit)return `<section class="about"><h1>作品管理</h1><p>此页面仅供作品集所有者使用。</p><a class="action" href="/signin-with-chatgpt?return_to=%2Fmanage" target="_top">登录后管理作品 ↗</a></section>`;
 return `<section class="manager"><div class="manager-heading"><div><div class="eyebrow">YOUR PORTFOLIO / 作品管理</div><h1>让作品保持更新。</h1><p>选择作品，替换素材或修改说明。点击“保存并更新”后，作品页即会更新。</p></div><a class="text-link" href="/" target="_blank" rel="noopener">查看作品集 ↗</a></div>${settingsManager()}${orderManager()}<div class="editor-layout"><aside class="project-picker"><label for="project-select">选择要编辑的作品</label><select id="project-select">${categories.map(c=>`<optgroup label="${esc(c.name)}">${projects.filter(p=>p.cat===c.id).map(p=>`<option value="${p.id}">${esc(p.title)}</option>`).join('')}</optgroup>`).join('')}</select><div id="edit-preview"></div><p class="editor-hint">素材上传后，点击保存才会替换作品页内容。<br>未填写的说明不会在作品页显示。</p></aside><div id="edit-panel"></div></div></section>`;}
function initEditor(){if(!canEdit)return;const select=document.querySelector('#project-select');if(!select)return;select.addEventListener('change',()=>{if(editorBusy){select.value=editingProject.id;return}if(editorDirty&&!confirm('当前修改尚未保存。确定切换作品并放弃这些修改吗？')){select.value=editingProject.id;return}editProject(select.value)});editProject(select.value);initOrder();}
function editProject(id){editingProject=structuredClone(projects.find(p=>p.id===id));editorDirty=false;const p=editingProject;
 document.querySelector('#edit-panel').innerHTML=`<form id="project-form"><div class="editor-toolbar"><span id="save-state" role="status">已加载作品</span><button class="action" type="submit">保存并更新 ↗</button></div><section class="editor-section"><h2>作品素材</h2><div class="upload-options"><label class="upload-card">替换封面<input type="file" id="cover-file" accept="image/jpeg,image/png,image/webp"><span>JPG / PNG / WebP，最大 25 MB</span></label><label class="upload-card">替换 / 上传视频<input type="file" id="video-file" accept="video/mp4,video/webm"><span>MP4 / WebM，最大 2 GB</span></label><label class="upload-card">添加项目图片<input type="file" id="image-files" accept="image/jpeg,image/png,image/webp" multiple><span>最多 30 张，可调整顺序</span></label></div><div id="upload-status" role="status" aria-live="polite"></div><div id="edit-media"></div></section><section class="editor-section"><h2>项目说明</h2><div class="editor-fields">${editorFields.map(([key,label])=>`<label class="${['title','type','tools'].includes(key)?'short-field':''}">${label}${['title','type','tools'].includes(key)?`<input name="${key}" value="${esc(p[key]||'')}" ${key==='title'?'required':''} maxlength="12000">`:`<textarea name="${key}" rows="${key==='intro'?3:4}" maxlength="12000">${esc(p[key]||'')}</textarea>`}${['idea','process','challenge','solution'].includes(key)?'<span>在作品页中默认收起，点击展开</span>':''}</label>`).join('')}</div></section><div class="editor-toolbar bottom-toolbar"><span>保存后更新线上作品集</span><button class="action" type="submit">保存并更新 ↗</button></div></form>`;
 document.querySelector('#project-form').addEventListener('submit',saveEditor);document.querySelector('#project-form').addEventListener('input',()=>{editorDirty=true;setSaveState('有尚未保存的修改')});
 document.querySelector('#cover-file').onchange=e=>uploadFiles(e.target.files,'cover');document.querySelector('#video-file').onchange=e=>uploadFiles(e.target.files,'video');document.querySelector('#image-files').onchange=e=>uploadFiles(e.target.files,'images');refreshEditorMedia();
}
function setSaveState(text,error=false){const el=document.querySelector('#save-state');if(el){el.textContent=text;el.classList.toggle('error-text',error)}}
function refreshEditorMedia(){const p=editingProject;document.querySelector('#edit-preview').innerHTML=`<img src="${esc(imageUrl(p.cover||p.images[0]))}" alt="当前作品封面"><h2>${esc(p.title)}</h2><a class="text-link" href="./#/category/${p.cat}" target="_blank" rel="noopener">查看分类页 ↗</a>`;
 document.querySelector('#edit-media').innerHTML=`${p.video?`<div class="editor-video"><video controls preload="metadata" playsinline src="${esc(p.video)}" poster="${esc(imageUrl(p.cover||p.images[0]))}"></video><button type="button" id="remove-video" class="small-button">移除影片</button></div>`:'<p class="editor-hint">尚未设置影片，可在上方上传。</p>'}<div class="editor-gallery">${p.images.map((src,i)=>`<div class="editor-image">${image(src,'项目图片 '+(i+1))}<div><button class="small-button" type="button" data-reorder="${i}" data-direction="-1" ${i===0?'disabled':''} aria-label="图片 ${i+1} 前移">←</button><button class="small-button" type="button" data-reorder="${i}" data-direction="1" ${i===p.images.length-1?'disabled':''} aria-label="图片 ${i+1} 后移">→</button><button class="small-button" type="button" data-remove-image="${i}">移除</button></div></div>`).join('')}</div>`;
 document.querySelector('#remove-video')?.addEventListener('click',()=>{p.video='';editorDirty=true;setSaveState('影片已从草稿移除，保存后生效');refreshEditorMedia()});
 document.querySelectorAll('[data-remove-image]').forEach(b=>b.onclick=()=>{if(editorBusy)return;p.images.splice(Number(b.dataset.removeImage),1);editorDirty=true;setSaveState('有尚未保存的修改');refreshEditorMedia()});
 document.querySelectorAll('[data-reorder]').forEach(b=>b.onclick=()=>{if(editorBusy)return;const i=Number(b.dataset.reorder),j=i+Number(b.dataset.direction);[p.images[i],p.images[j]]=[p.images[j],p.images[i]];editorDirty=true;setSaveState('有尚未保存的修改');refreshEditorMedia()});
}
function busy(value){editorBusy=value;document.querySelectorAll('#project-form button[type=submit],#project-form input[type=file],#project-select').forEach(el=>el.disabled=value)}
async function uploadOne(file,progress,signal){let session;try{session=await api('/api/uploads',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({name:file.name,type:file.type,size:file.size}),signal});const parts=[];for(let start=0,index=1;start<file.size;start+=session.chunkSize,index++){const blob=file.slice(start,start+session.chunkSize);let result;for(let attempt=0;attempt<3;attempt++){try{result=await api('/api/uploads/'+session.id+'?part='+index,{method:'PUT',headers:{'Content-Type':'application/octet-stream'},body:blob,signal});break}catch(e){if(signal.aborted||e.status&&e.status<500||attempt===2)throw e;await new Promise(r=>setTimeout(r,1000*(attempt+1)))}}parts.push(result);progress(Math.min(start+blob.size,file.size)/file.size)}return await api('/api/uploads/'+session.id+'/complete',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({parts}),signal})}catch(e){if(session)fetch('/api/uploads/'+session.id,{method:'DELETE'}).catch(()=>{});throw e}}
async function uploadFiles(fileList,kind){if(!fileList?.length||editorBusy)return;const files=Array.from(fileList);if(kind==='images'&&editingProject.images.length+files.length>30){setSaveState('每个项目最多 30 张图片。',true);return}
 for(const file of files){const video=kind==='video';if(!(video?['video/mp4','video/webm']:['image/jpeg','image/png','image/webp']).includes(file.type)){setSaveState('文件格式不支持，请选择 MP4 / WebM 视频或 JPG / PNG / WebP 图片。',true);return}if(file.size>(video?2*1024**3:25*1024**2)){setSaveState(video?'单个视频最大 2 GB。':'单张图片最大 25 MB。',true);return}}
 busy(true);uploadAbort=new AbortController();const status=document.querySelector('#upload-status');status.innerHTML='<div class="upload-progress"><span></span><progress max="100" value="0"></progress><button type="button" class="small-button">取消上传</button></div>';status.querySelector('button').onclick=()=>uploadAbort.abort();
 try{for(let i=0;i<files.length;i++){const file=files[i];const result=await uploadOne(file,n=>{status.querySelector('span').textContent=`${file.name} · ${Math.round(n*100)}%（${i+1}/${files.length}）`;status.querySelector('progress').value=((i+n)/files.length)*100},uploadAbort.signal);
 if(kind==='images')editingProject.images.push(result.url);else editingProject[kind]=result.url;
 if(kind==='cover'){const im=new Image();im.src=result.url;await im.decode();editingProject.portrait=im.naturalHeight>im.naturalWidth*1.15;}
 editorDirty=true;refreshEditorMedia();}status.textContent='上传完成。点击“保存并更新”后发布到作品页。';setSaveState('素材已上传，尚未保存到作品页');}
 catch(e){status.textContent=uploadAbort.signal.aborted?'上传已取消，原作品保持不变。':e.message;setSaveState('上传未完成，已保留当前编辑内容。',true)}finally{busy(false);uploadAbort=null;document.querySelectorAll('input[type=file]').forEach(el=>el.value='')}
}
async function saveEditor(event){event?.preventDefault();if(editorBusy||!editingProject)return;const form=document.querySelector('#project-form');if(!form.reportValidity())return;busy(true);setSaveState('正在保存…');const p={...editingProject,...Object.fromEntries(new FormData(form).entries())};try{const result=await api('/api/projects/'+p.id,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});p._revision=result.revision;editingProject=p;projects=projects.map(x=>x.id===p.id?p:x);editorDirty=false;setSaveState('已保存，作品页已更新');refreshEditorMedia();refreshProjectPicker();renderOrderList()}catch(e){setSaveState(e.message,true)}finally{busy(false)}}
window.addEventListener('beforeunload',e=>{if(editorDirty||editorBusy||orderDirty||orderBusy||settingsDirty||settingsBusy){e.preventDefault();e.returnValue=''}});
let orderRevisions={},orderCategory='',orderDraft=[],orderDirty=false,orderBusy=false,draggedProject=null;
function orderManager(){return `<details class="order-manager"><summary>作品排序 <span>调整每个分类中作品的展示顺序</span></summary><div class="order-body"><label for="order-category">选择分类</label><select id="order-category">${categories.map(c=>`<option value="${c.id}">${esc(c.name)}</option>`).join('')}</select><p class="editor-hint">拖动作品调整顺序，也可以点击上移、下移、置顶或置底。调整后点击“保存排序”，作品页即会更新。</p><ol id="order-list" aria-label="作品展示顺序"></ol><div class="order-toolbar"><span id="order-state" role="status" aria-live="polite">当前为已保存顺序</span><div><button id="order-reset" type="button" class="small-button">撤销调整</button><button id="order-save" type="button" class="action">保存排序 ↗</button></div></div></div></details>`}
function initOrder(){const select=document.querySelector('#order-category');if(!select)return;orderBusy=false;select.onchange=()=>{if(orderBusy||orderDirty&&!confirm('当前排序尚未保存。确定切换分类并放弃调整吗？')){select.value=orderCategory;return}loadOrder(select.value)};document.querySelector('#order-save').onclick=saveOrderEditor;document.querySelector('#order-reset').onclick=()=>{if(!orderBusy)loadOrder(orderCategory)};loadOrder(select.value)}
function loadOrder(cat){orderCategory=cat;orderDraft=projects.filter(p=>p.cat===cat).map(p=>p.id);orderDirty=false;renderOrderList();orderState('当前为已保存顺序')}
function orderState(text,error=false){const el=document.querySelector('#order-state');if(el){el.textContent=text;el.classList.toggle('error-text',error)}document.querySelector('#order-save').disabled=orderBusy||!orderDirty;document.querySelector('#order-reset').disabled=orderBusy||!orderDirty;document.querySelector('#order-category').disabled=orderBusy;document.querySelectorAll('#order-list button').forEach(b=>b.disabled=orderBusy||b.dataset.edge==='true');document.querySelectorAll('#order-list li').forEach(li=>li.draggable=!orderBusy)}
function moveProject(id,to){if(orderBusy)return;const from=orderDraft.indexOf(id);if(from<0||to<0||to>=orderDraft.length||from===to)return;orderDraft.splice(from,1);orderDraft.splice(to,0,id);orderDirty=true;renderOrderList();orderState('顺序已调整，点击“保存排序”后生效');document.querySelector(`[data-order-id="${id}"]`)?.focus({preventScroll:true})}
function renderOrderList(){const list=document.querySelector('#order-list');if(!list)return;list.innerHTML=orderDraft.map((id,i)=>{const p=projects.find(p=>p.id===id);return `<li draggable="${!orderBusy}" data-order-id="${id}" tabindex="-1"><span class="order-number">${String(i+1).padStart(2,'0')}</span>${image(p.cover||p.images[0],p.title+'封面')}<span class="order-title">${esc(p.title)}</span><div class="order-buttons">${[['first','置顶',i===0],['up','上移',i===0],['down','下移',i===orderDraft.length-1],['last','置底',i===orderDraft.length-1]].map(([action,label,edge])=>`<button type="button" class="small-button" data-move="${action}" data-edge="${edge}" ${edge||orderBusy?'disabled':''} aria-label="${esc(p.title)}${label}">${label}</button>`).join('')}</div></li>`}).join('');list.onclick=e=>{const b=e.target.closest('[data-move]');if(!b)return;const id=b.closest('li').dataset.orderId,i=orderDraft.indexOf(id);moveProject(id,{first:0,up:i-1,down:i+1,last:orderDraft.length-1}[b.dataset.move])};list.ondragstart=e=>{const li=e.target.closest('li');if(!li||orderBusy||e.target.closest('button')){e.preventDefault();return}draggedProject=li.dataset.orderId;e.dataTransfer.setData('text/plain',draggedProject);e.dataTransfer.effectAllowed='move';li.classList.add('dragging')};list.ondragover=e=>{if(draggedProject&&!orderBusy){e.preventDefault();e.dataTransfer.dropEffect='move'}};list.ondrop=e=>{e.preventDefault();const target=e.target.closest('li');if(target&&draggedProject)moveProject(draggedProject,orderDraft.indexOf(target.dataset.orderId));draggedProject=null};list.ondragend=()=>{draggedProject=null;list.querySelectorAll('.dragging').forEach(el=>el.classList.remove('dragging'))}}
function refreshProjectPicker(){const select=document.querySelector('#project-select');if(!select)return;const selected=select.value;select.innerHTML=categories.map(c=>`<optgroup label="${esc(c.name)}">${projects.filter(p=>p.cat===c.id).map(p=>`<option value="${p.id}">${esc(p.title)}</option>`).join('')}</optgroup>`).join('');select.value=selected}
async function saveOrderEditor(){if(orderBusy||!orderDirty)return;orderBusy=true;orderState('正在保存排序…');try{const result=await api('/api/order/'+orderCategory,{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({ids:orderDraft,_revision:orderRevisions[orderCategory]||0})});orderRevisions[orderCategory]=result.revision;const sorted=orderDraft.map(id=>projects.find(p=>p.id===id));let i=0;projects=projects.map(p=>p.cat===orderCategory?sorted[i++]:p);orderDirty=false;refreshProjectPicker();orderBusy=false;orderState('排序已保存，作品页已更新')}catch(e){orderBusy=false;orderState(e.message,true)}}

